# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MoneyMonkey' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MoneyMonkey

  target 'MoneyMonkeyTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MoneyMonkeyUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
